apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  claimRef:
    name: postgres-pv-claim
    namespace: devops-tools
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: devops-tools
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  claimRef:
    name: sonar-pv-claim
    namespace: devops-tools
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/sonar
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-pv-claim
  namespace: devops-tools
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: devops-tools
  labels:
    app: postgresdb
spec:
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
  selector:
    app: postgresdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: devops-tools
spec:
  selector:
    matchLabels:
      app: postgresdb
  serviceName: "postgresdb"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgres-pod
        image: postgres:latest
        ports:
        - containerPort: 5432
          name: postgresdb
        env:
        - name: POSTGRES_USER
          value: sonarqube
        - name: POSTGRES_PASSWORD
          value: "admin123"
        - name: POSTGRES_DB
          value: "sonardb"
        - name: PGDATA
          value: /var/lib/postgresql/data/sonardb
        volumeMounts:
        - name: postgres-pv-data
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: postgres-pv-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim

