apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: devops-tools
  labels:
    app: sonarqube
spec:
  ports:
  - protocol: TCP
    name: sonarqube
    nodePort: 32001
    targetPort: 9000
    port: 9000
  type: NodePort
  selector:
    app: sonarqube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarqube-deployment
  name: sonarqube
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        -
          env:
            -
              name: SONARQUBE_JDBC_USERNAME
              value: sonarqube
            -
              name: SONARQUBE_JDBC_URL
              value: "jdbc:postgresql://10.109.21.188:5432/sonardb"
            -
              name: SONARQUBE_JDBC_PASSWORD
              value: admin123
          image: "sonarqube:latest"
          name: sonarqube-pod
          ports:
            -
              containerPort: 9000
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 1024Mi
          volumeMounts:
            -
              mountPath: /opt/sonarqube/data/
              name: sonarqube-data
            -
              mountPath: /opt/sonarqube/extensions/
              name: sonarqube-extensions
      volumes:
        -
          name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonar-pv-data-claim
        -
          name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: sonar-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-pv-data-claim
  namespace: devops-tools
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv-data-volume
  labels:
    type: local
spec:
  storageClassName: manual
  claimRef:
    name: sonar-pv-data-claim
    namespace: devops-tools
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/sonardata

